version: '3.9'
services:
  app:
    build: .. # Adjust if your Dockerfile is elsewhere
    container_name: llm-financial-agent
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=financedb
      - POSTGRES_USER=financeuser
      - POSTGRES_PASSWORD=StrongPassword123
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: StrongPassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
