apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-financial-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-financial-agent
  template:
    metadata:
      labels:
        app: llm-financial-agent
    spec:
      containers:
      - name: app
        image: <your-ecr-repo>/llm-financial-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: financedb
        - name: POSTGRES_USER
          value: financeuser
        - name: POSTGRES_PASSWORD
          value: StrongPassword123
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: llm-financial-agent
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: llm-financial-agent
