apiVersion: apps/v1
kind: Deployment
metadata:
  name: reasoner-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reasoner-agent
  template:
    metadata:
      labels:
        app: reasoner-agent
    spec:
      containers:
      - name: reasoner-agent
        image: reasoner-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: RETRIEVER_URL
          value: http://retriever-agent:8000
        - name: REDIS_HOST
          value: redis
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: financedb
        - name: POSTGRES_USER
          value: financeuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: reasoner-agent
spec:
  selector:
    app: reasoner-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
